export const Skill_data = [
  {
    skill_name: "Html 5",
    Image: "/html.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Css",
    Image: "/css.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "JavaScript",
    Image: "/js.png",
    width: 65,
    height: 65,
  },
  {
    skill_name: "React",
    Image: "/react.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Next.js",
    Image: "/next.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Tailwind CSS",
    Image: "/tailwind.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Node.js",
    Image: "/node-js.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "MongoDB",
    Image: "/mongodb.png",
    width: 40,
    height: 40,
  },
  {
    skill_name: "Python",
    Image: "/python.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "C#",
    Image: "/csharp.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "ASP.NET Core",
    Image: "/dotnet.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Java",
    Image: "/java.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Typescript",
    Image: "/ts.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Framer Motion",
    Image: "/framer.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "MySQL",
    Image: "/mysql.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "AWS",
    Image: "/aws.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Git",
    Image: "/git-white.png",
    width: 80,
    height: 80,
  },
];
